# -*- coding: utf-8 -*-
"""Problem 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kVErSqqr7SyrqikBgoi6iQ33_H8dw2Di
"""

import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image
# Create 3 random matrices with sizes 3x5
# Random number between 0 and 255 using 8-bit unsigned integers

# R = np.random.randint(255,size =(512,512),dtype=np.uint8)
# G = np.random.randint(255,size =(512,512),dtype=np.uint8)
# B = np.random.randint(255,size =(512,512),dtype=np.uint8)

R=( [ 51, 37, 43, 49, 53],
      [ 91, 93, 65, 60, 60],
      [ 86, 70, 66, 51, 50] )

G=( [ 27, 34, 27, 21, 27],
      [ 23, 14, 4, 9, 23],
      [ 7, 9, 7, 0, 0] )

B=( [ 53, 36, 40, 44, 48],
      [ 79, 77, 51, 51, 53],
      [ 67, 46, 45, 40, 43] )


# Combine these three matrices (3 x 5 x 3) size using Numpy - order BGR
rgb = np.dstack((R,G,B))

img = Image.fromarray((rgb * 255).astype(np.uint8))
# img = Image.fromarray(rgb)
img.save('myimg.jpeg')